services:
  tp-vue-front:
    image: tp-vue-front:latest
    build:
      context: ../my-project
      dockerfile: deployment/Dockerfile
      args:
        VITE_BACKEND_URL: http://78.138.58.95/B3dev-TP_VUE
        VITE_FRONTEND_URL: http://78.138.58.95/B3dev-TP_VUE/
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - tp-vue-api

  tp-vue-api:
    image: tp-vue-api:latest
    build:
      context: ../express-project
      dockerfile: deployment/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:3003:3000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/B3devTPVue
      VITE_FRONTEND_ORIGIN: http://78.138.58.95
      VITE_FRONTEND_URL: http://78.138.58.95/B3dev-TP_VUE/
      VITE_BACKEND_URL: http://78.138.58.95/B3dev-TP_VUE
