version: '3.8'

services:
  tp-vue-api:
    build:
      context: ./B3dev-TP_VUE/express-project
      dockerfile: deployment/Dockerfile
    container_name: tp-vue-api
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=test

  tp-vue-front:
    build:
      context: ./B3dev-TP_VUE/my-project
      dockerfile: deployment/Dockerfile
    container_name: tp-vue-front
    ports:
      - "8080:80"

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data/mongo:/data/db