version: '3.8'

services:
  B3dev-TP_vue-api:
    build:
      context: ./B3dev-TP_vue/express-project
      dockerfile: deployment/Dockerfile
    container_name: B3dev-TP_vue-api
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=test

  B3dev-TP_vue:
    build:
      context: ./B3dev-TP_vue/my-project
      dockerfile: deployment/Dockerfile
    container_name: B3dev-TP_vue-front
    ports:
      - "8080:80"

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data/mongo:/data/db